/* Generated By:JavaCC: Do not edit this line. CTLParserTreeConstants.java Version 7.0.10 */
package edu.txstate.ctl_parser.util.javacc_parser;

public interface CTLParserTreeConstants {
    public int JJTFORMULA = 0;
    public int JJTVOID = 1;
    public int JJTEXPR = 2;
    public int JJTCONNECTIVE = 3;
    public int JJTATOM = 4;


    public String[] jjtNodeName = {
            "Formula",
            "void",
            "Expr",
            "Connective",
            "Atom",
    };
}
/* JavaCC - OriginalChecksum=8c7fb5161ea70e2c66a9141f7326104c (do not edit this line) */
